#!/bin/bash -e

vercomp () {
    if [[ $1 == $2 ]]; then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)

    # Fill empty fields in ver1 with zeros.
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++)); do
        ver1[i]=0
    done

    for ((i=0; i<${#ver1[@]}; i++)); do
        if [[ -z ${ver2[i]} ]]; then
            # Fill empty fields in ver2 with zeros.
            ver2[i]=0
        fi

        if ((10#${ver1[i]} > 10#${ver2[i]})); then
            return 1
        fi

        if ((10#${ver1[i]} < 10#${ver2[i]})); then
            return 2
        fi
    done

    return 0
}


##############################################################################

if [ -z $VIRTUAL_ENV ]; then
    . ./startenv
fi

# pip setup
pip install --upgrade pip setuptools
yes w | pip install --upgrade -r requirements/dev.txt

# Node packages.
if [ -e package.json ]; then
    # Upgrade npm if necessary.
    MINIMUM_VERSION=5
    NPM_VERSION=`npm -v`

    # Compare current npm version.
    vercomp $NPM_VERSION $MINIMUM_VERSION
    COMPARISON_RESULT=$?

    if [ "$COMPARISON_RESULT" -eq "2"]; then
        echo "\npm should be equal or greater than $MINIMUM_VERSION"
        echo "Current version: $NPM_VERSION. Upgrading npm."
        echo "Superuser rights are required."
        sudo npm i -g npm
    fi

    npm install
fi
