#!/bin/bash -e
# Start the virtualenv for the current project
#
# If no virtualenv has been installed this script will:
#  - Install `pyenv` if not installed already.
#  - Download the required version of Python.
#  - Initialize a new virtualenv.
#
# This script only works with Python 3.

PYTHON_VERSION=3.6.1
PYENV_ROOT="$HOME/.pyenv"
VIRTUALENV_DIR="./python_env"


function export_pyenv_variables {
    export PYENV_ROOT=$PYENV_ROOT
    export PATH="$PYENV_ROOT/bin:$PATH"
}

# Install a package if it's not present
# Usage: install_package binary [package]
# Checks if "which binary" is successful, if not, installs the package
# If package isn't given, defaults to the same name as binary
function install_package {
    BINARY=$1
    PACKAGE=${2:-$BINARY}
    if [ -z "$(which $BINARY 2>/dev/null)" ]
    then
        case "$PACKAGE" in
            pyenv)
                echo "Installing pyenv"
                curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
                pyenv init -
                pyenv update
                ;;
            brew)
                ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
                export PATH=$PATH:/usr/local/bin
                ;;
            *)
                if [ "$(uname -s)" = "Darwin" ]
                then
                    brew install $PACKAGE
                else
                    found=$(dpkg -l $PACKAGE | grep -qv "no packages found matching" || echo 1)

                    if [ ! $found = "" ]; then
                        echo "Installing $PACKAGE"
                        sudo apt-get -y -qq install $PACKAGE
                    fi
                fi
                ;;
        esac
    else
        case "$PACKAGE" in
            pyenv)
                eval "$(pyenv init -)"
                ;;
        esac
    fi
}


function install_python(){
    install_package pyenv

    if ( pyenv versions --bare | grep -E \^$PYTHON_VERSION\$ ) >& /dev/null; then
        echo "Python version $PYTHON_VERSION is already installed. Skip installation."
    else
        echo "Installing python version $PYTHON_VERSION ..."
        pyenv install $PYTHON_VERSION
    fi

    # This ensures installed python versions and binaries properly shimmed.
    pyenv rehash

    pyenv shell $PYTHON_VERSION

    echo "Current active python version" $(pyenv shell).
}


################################################################################
# Execution starts here.
################################################################################

# Export pyenv paths so that the binary can be found.
export_pyenv_variables

if [ -z $VIRTUAL_ENV ]; then
    if [ -f "$VIRTUALENV_DIR/bin/activate" ]; then
        . ./$VIRTUALENV_DIR/bin/activate
    else
        install_python

        # Create virtualenv.
        python -m venv $VIRTUALENV_DIR

        . $VIRTUALENV_DIR/bin/activate

        ./refreshenv
    fi

    if [ -e package.json ]; then
        export PATH=$PATH:`npm bin`
    fi
else
    echo "Already in a virtualenv. Not doing anything!"
fi

################################################################################
# List system packages to install.
################################################################################
# install_package python-dev
